### PR TITLE
GLNX_ESYSCALL: New wrapper for system calls

### PR DESCRIPTION
**Pull request by cgwalters**
Avoids a lot of duplicate code...but is it worth the obfuscation?

### CODE REVIEW

**Comment by aruiz** [comment]
Pull requests are not allowed in the mirror I'm afraid :( (there's no way to disable them)

**Comment by cgwalters** [comment]
Is that an automated comment?  I am using PRs against the mirror, and this is my project =)

**Comment by aruiz** [comment]
It is not automated, we shouldn't be using these really. What's the value of the PR if you can't merge? We ought to be using Bugzilla for this. The mirror was never intended to replace Bugzilla for patch reviewing.

**Comment by cgwalters** [comment]
Sadly it has for at least ostree...there's a rather strong gravitational pull around github now.  

PRs are a familar workflow to many many people now, and are rather objectively less painful to submit and review than git-bz.  And I'm fine with merges not working (I prefer no merge commits), I just do merging by hand.

Don't get me wrong, I don't find the state of things really satisfactory either...

**Pull request closed without merging**
