### PR TITLE
tree-wide: Use our own syscall wrappers or error prefixing

### PR DESCRIPTION
**Pull request by cgwalters**
Followup to similar commits in the ostree stack recently.

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to libglnx!

libglnx uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers
and follow the instructions there to upload your change to Bugzilla.

**Comment by jlebon** [comment]
Typo in commit title: `s/or/for/`. Otherwise LGTM!

**Comment by cgwalters** [comment]
Ah the `or` was intentional...right?

**Comment by cgwalters** [comment]
Our syscall wrappers usually do prefixing, so if we're not using them we need to do it is what I meant.

**Comment by jlebon** [comment]
Hah, gotcha. Nevermind then.

**Comment by cgwalters** [comment]
Pushed with an added `,` in the msg, thanks!

**Pull request closed without merging**
