### PR TITLE
tests/xattrs: Skip on filesystems with no user xattr support

### PR DESCRIPTION
**Pull request by cgwalters**
Like tmpfs.

See: https://github.com/flatpak/flatpak/issues/686

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to libglnx!

libglnx uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Comment by cgwalters** [comment]
@alexlarsson want to give this a :+1: ?

**Comment by alexlarsson** [comment]
Looks good to me.

**Comment by cgwalters** [comment]
Merged, thanks!

**Pull request closed without merging**
