### PR TITLE
Makefile-libglnx.am: use README.md not README

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano gscrivan@redhat.com

### CODE REVIEW

**Comment by giuseppe** [comment]
this is needed to fix make dist in ostree

**Comment by cgwalters** [comment]
:+1:  merged.  (Though do note I don't use `make dist` myself generally, I use `git archive`)

**Comment by cgwalters** [comment]
@giuseppe You need to close this, since at the moment no one else has admin rights for this project.

**Comment by giuseppe** [comment]
yes, sorry, closing now.

**Pull request closed without merging**
