### PR TITLE
Remove libcontainer

### PR DESCRIPTION
**Pull request by cgwalters**
No longer used by anything; see https://github.com/projectatomic/rpm-ostree/pull/429

### CODE REVIEW

**Comment by jlebon** [comment]
:+1:

**Comment by jlebon** [comment]
I don't suppose there'd be other consumers of this?

**Comment by jlebon** [comment]
Might want to also remove this line from the README:

> - Some basic container utility functions

**Comment by cgwalters** [comment]
No other consumers AFAICS in NetworkManager/flatpak/ostree.  Removed the bit in the README and pushed, thanks!

**Pull request closed without merging**
