### PR TITLE
fdio: deleting .tmp file on failure

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Added a quick check for failed replace_content to delete tmp file (if exists).

### CODE REVIEW

**Comment by cgwalters** [comment]
The patch is simple and correct and I've pushed it, thanks!

However I am extremely picky about commit messages :smile:  I reworded it here: https://github.com/GNOME/libglnx/commit/a6d08657aa868a0d5c7b5dd494e16f65415a148f

Changes:
- Use the "imperative" voice for the subject
- Describe in the commit body the real world problem so that someone later knows who is using it and why
- Add a quick note about possible future changes

**Comment by cgwalters** [comment]
By the way due to weird issues with the way the GNOME github mirroring works I don't have perms to close this PR, so you'll need to do that.

**Comment by cgwalters** [comment]
More on commit messages in http://chris.beams.io/posts/git-commit/

**Comment by yuqi-zhang** [comment]
Ah sorry, I will watch for formatting in the future! Is it safe for me to just close this PR as is?

**Comment by cgwalters** [comment]
Yep, it's pushed in master, we can close this.

(Though we will need to bump the submodule in ostree)

**Comment by yuqi-zhang** [comment]
I see, should I operate the update for the submodule?

**Pull request closed without merging**
