### PR TITLE
listxattr: Don't assume that first call to listxattr gives correct size

### PR DESCRIPTION
**Pull request by wmanley**
To get the right sized buffer to pass to `flistattr` and `llistattr` we
first call them with a zero byte buffer.  They then return the number of
bytes they'll actually need to operate.  We would `malloc` and then call
again assuming that the size we got originally was correct.

On my computer at least this isn't always the case.  I've seen instances
where the first call returns 23B, but then on the second one returns no
data at all.  Getting these non-existant xattrs would then cause ostree
to fail.

I'm not sure why it's behaving this way on my machine.  I suspect its some
interaction with overlayfs but I haven't proven this.

### CODE REVIEW

**Comment by cgwalters** [comment]
Well, even without kernel bugs this could happen in the face of concurrency - if another program is changing an xattr as we read it.  overlayfs might make this more likely since it uses xattrs internally.

**Comment by cgwalters** [comment]
I think if we open the patient for this we should likely make it a retry loop - use the initial call to get the expected size, but if the later call fails with `ERANGE`, double the buffer and try again. 

And do the same for `getxattr()` and *also* silently ignore `ENOATTR` from `getxattr()` and continue.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to libglnx!

libglnx uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Comment by cgwalters** [comment]
Ah...I do use PR reviews here.

**Comment by cgwalters** [comment]
Well, whatever, it doesn't matter that much, we can discuss on the closed PR.  At some point I may try to migrate to github.

**Comment by cgwalters** [comment]
Moved this to #32

**Pull request closed without merging**
